name: Test Workflow with Push and Dispatch

on:
  push:
    branches:
      - main  # Change this to your branch if needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Echo
        run: echo "Hello, world!"
